/*
 * This file was autogenerated by TinyMPC on Mon Oct 21 13:08:42 2024
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_solver;

#ifdef __cplusplus
}
#endif
